### ISSUE TITLE
Remove unused ores from ore sorter products or add option to select which ores should ore sorter produce

### ISSUE THREAD

**Issue by WideMann** [SymmetricDevs/Supersymmetry-Ideas#105]
Ore sorter gives many now useless ores as a product. I suggest removing them for now and later adding them back when usage for them is found. The unused ore are:
 - from Orthomagmatic deposit: Thortveitite, Mineral-Rich Sand, Alluvial Euxenite
 - from Magmatic Hydrothermal deposit: Alluvial Bastnasite, Uraninite
 - from Sedimentary deposit: Caliche, Uraninite
 - from Hydrothermal deposit: Alluvial Xenotime
 - from Alluvial deposit: Alluvial Monazite, Mineral-Rich Sand
Or add built-in option to automatically void unwanted ores (drag from JEI to "ore filter" the ores you want to keep/void)

**Comment by divine-ray** [comment]
*hopefully* adressed in #972 (https://github.com/SymmetricDevs/Supersymmetry/pull/972)

**Comment by divine-ray** [comment]
Closing this since https://github.com/SymmetricDevs/Supersymmetry/pull/972 got merged.
